package org.zimnat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BatchStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchStatusAllPropertiesEquals(BatchStatus expected, BatchStatus actual) {
        assertBatchStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertBatchStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchStatusAllUpdatablePropertiesEquals(BatchStatus expected, BatchStatus actual) {
        assertBatchStatusUpdatableFieldsEquals(expected, actual);
        assertBatchStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchStatusAutoGeneratedPropertiesEquals(BatchStatus expected, BatchStatus actual) {
        assertThat(expected)
            .as("Verify BatchStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchStatusUpdatableFieldsEquals(BatchStatus expected, BatchStatus actual) {
        assertThat(expected)
            .as("Verify BatchStatus relevant properties")
            .satisfies(e -> assertThat(e.getPartnerReference()).as("check partnerReference").isEqualTo(actual.getPartnerReference()))
            .satisfies(e -> assertThat(e.getTheDate()).as("check theDate").isEqualTo(actual.getTheDate()))
            .satisfies(e -> assertThat(e.getTheVersion()).as("check theVersion").isEqualTo(actual.getTheVersion()))
            .satisfies(e -> assertThat(e.getPartnerToken()).as("check partnerToken").isEqualTo(actual.getPartnerToken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchStatusUpdatableRelationshipsEquals(BatchStatus expected, BatchStatus actual) {
        assertThat(expected)
            .as("Verify BatchStatus relationships")
            .satisfies(e -> assertThat(e.getRequest()).as("check request").isEqualTo(actual.getRequest()));
    }
}
