package org.zimnat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LICQuoteRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteRequestAllPropertiesEquals(LICQuoteRequest expected, LICQuoteRequest actual) {
        assertLICQuoteRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertLICQuoteRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteRequestAllUpdatablePropertiesEquals(LICQuoteRequest expected, LICQuoteRequest actual) {
        assertLICQuoteRequestUpdatableFieldsEquals(expected, actual);
        assertLICQuoteRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteRequestAutoGeneratedPropertiesEquals(LICQuoteRequest expected, LICQuoteRequest actual) {
        assertThat(expected)
            .as("Verify LICQuoteRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteRequestUpdatableFieldsEquals(LICQuoteRequest expected, LICQuoteRequest actual) {
        assertThat(expected)
            .as("Verify LICQuoteRequest relevant properties")
            .satisfies(e -> assertThat(e.getTheFunction()).as("check theFunction").isEqualTo(actual.getTheFunction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteRequestUpdatableRelationshipsEquals(LICQuoteRequest expected, LICQuoteRequest actual) {
        assertThat(expected)
            .as("Verify LICQuoteRequest relationships")
            .satisfies(e -> assertThat(e.getVehicles()).as("check vehicles").isEqualTo(actual.getVehicles()));
    }
}
