package org.zimnat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LICQuoteUpdateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteUpdateAllPropertiesEquals(LICQuoteUpdate expected, LICQuoteUpdate actual) {
        assertLICQuoteUpdateAutoGeneratedPropertiesEquals(expected, actual);
        assertLICQuoteUpdateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteUpdateAllUpdatablePropertiesEquals(LICQuoteUpdate expected, LICQuoteUpdate actual) {
        assertLICQuoteUpdateUpdatableFieldsEquals(expected, actual);
        assertLICQuoteUpdateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteUpdateAutoGeneratedPropertiesEquals(LICQuoteUpdate expected, LICQuoteUpdate actual) {
        assertThat(expected)
            .as("Verify LICQuoteUpdate auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteUpdateUpdatableFieldsEquals(LICQuoteUpdate expected, LICQuoteUpdate actual) {
        assertThat(expected)
            .as("Verify LICQuoteUpdate relevant properties")
            .satisfies(e -> assertThat(e.getPartnerReference()).as("check partnerReference").isEqualTo(actual.getPartnerReference()))
            .satisfies(e -> assertThat(e.getTheDate()).as("check theDate").isEqualTo(actual.getTheDate()))
            .satisfies(e -> assertThat(e.getTheVersion()).as("check theVersion").isEqualTo(actual.getTheVersion()))
            .satisfies(e -> assertThat(e.getPartnerToken()).as("check partnerToken").isEqualTo(actual.getPartnerToken()))
            .satisfies(e -> assertThat(e.getLicenceID()).as("check licenceID").isEqualTo(actual.getLicenceID()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()))
            .satisfies(e -> assertThat(e.getDeliveryMethod()).as("check deliveryMethod").isEqualTo(actual.getDeliveryMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLICQuoteUpdateUpdatableRelationshipsEquals(LICQuoteUpdate expected, LICQuoteUpdate actual) {}
}
