package org.zimnat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResponsesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsesAllPropertiesEquals(Responses expected, Responses actual) {
        assertResponsesAutoGeneratedPropertiesEquals(expected, actual);
        assertResponsesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsesAllUpdatablePropertiesEquals(Responses expected, Responses actual) {
        assertResponsesUpdatableFieldsEquals(expected, actual);
        assertResponsesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsesAutoGeneratedPropertiesEquals(Responses expected, Responses actual) {
        assertThat(expected)
            .as("Verify Responses auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsesUpdatableFieldsEquals(Responses expected, Responses actual) {
        assertThat(expected)
            .as("Verify Responses relevant properties")
            .satisfies(e -> assertThat(e.getResult()).as("check result").isEqualTo(actual.getResult()))
            .satisfies(e -> assertThat(e.getMessage()).as("check message").isEqualTo(actual.getMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponsesUpdatableRelationshipsEquals(Responses expected, Responses actual) {}
}
