package org.zimnat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TPILICQuoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTPILICQuoteAllPropertiesEquals(TPILICQuote expected, TPILICQuote actual) {
        assertTPILICQuoteAutoGeneratedPropertiesEquals(expected, actual);
        assertTPILICQuoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTPILICQuoteAllUpdatablePropertiesEquals(TPILICQuote expected, TPILICQuote actual) {
        assertTPILICQuoteUpdatableFieldsEquals(expected, actual);
        assertTPILICQuoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTPILICQuoteAutoGeneratedPropertiesEquals(TPILICQuote expected, TPILICQuote actual) {
        assertThat(expected)
            .as("Verify TPILICQuote auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTPILICQuoteUpdatableFieldsEquals(TPILICQuote expected, TPILICQuote actual) {
        assertThat(expected)
            .as("Verify TPILICQuote relevant properties")
            .satisfies(e -> assertThat(e.getPartnerReference()).as("check partnerReference").isEqualTo(actual.getPartnerReference()))
            .satisfies(e -> assertThat(e.getTheDate()).as("check theDate").isEqualTo(actual.getTheDate()))
            .satisfies(e -> assertThat(e.getTheVersion()).as("check theVersion").isEqualTo(actual.getTheVersion()))
            .satisfies(e -> assertThat(e.getPartnerToken()).as("check partnerToken").isEqualTo(actual.getPartnerToken()))
            .satisfies(e -> assertThat(e.getFunction()).as("check function").isEqualTo(actual.getFunction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTPILICQuoteUpdatableRelationshipsEquals(TPILICQuote expected, TPILICQuote actual) {}
}
